# Generated by Django 4.1.5 on 2023-01-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
