# Generated by Django 4.1.5 on 2023-01-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_services_price_alter_services_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
