# Generated by Django 4.1.5 on 2023-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_financialstatements_stock_balancesheets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.TextField(default='aapl'),
            preserve_default=False,
        ),
    ]
