# Generated by Django 4.1.5 on 2023-01-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.TextField(default='AAPL'),
        ),
    ]
