# Generated by Django 4.1.5 on 2023-01-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_stock_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ticker',
        ),
    ]
