# Generated by Django 4.1.5 on 2023-01-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_remove_stock_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheets',
            name='financialstatements_ptr',
        ),
        migrations.RemoveField(
            model_name='cashflowstatements',
            name='financialstatements_ptr',
        ),
        migrations.RemoveField(
            model_name='incomestatements',
            name='financialstatements_ptr',
        ),
        migrations.AddField(
            model_name='balancesheets',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowstatements',
            name='id',
            field=models.BigAutoField(auto_created=True, default='AAPL', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomestatements',
            name='id',
            field=models.BigAutoField(auto_created=True, default='AAPL', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Financialstatements',
        ),
    ]
